// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package chat

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConnReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnReq) Reset()         { *m = ConnReq{} }
func (m *ConnReq) String() string { return proto.CompactTextString(m) }
func (*ConnReq) ProtoMessage()    {}
func (*ConnReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *ConnReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnReq.Unmarshal(m, b)
}
func (m *ConnReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnReq.Marshal(b, m, deterministic)
}
func (m *ConnReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnReq.Merge(m, src)
}
func (m *ConnReq) XXX_Size() int {
	return xxx_messageInfo_ConnReq.Size(m)
}
func (m *ConnReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConnReq proto.InternalMessageInfo

func (m *ConnReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GroupActionReq struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Action               string   `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupActionReq) Reset()         { *m = GroupActionReq{} }
func (m *GroupActionReq) String() string { return proto.CompactTextString(m) }
func (*GroupActionReq) ProtoMessage()    {}
func (*GroupActionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *GroupActionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupActionReq.Unmarshal(m, b)
}
func (m *GroupActionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupActionReq.Marshal(b, m, deterministic)
}
func (m *GroupActionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupActionReq.Merge(m, src)
}
func (m *GroupActionReq) XXX_Size() int {
	return xxx_messageInfo_GroupActionReq.Size(m)
}
func (m *GroupActionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupActionReq.DiscardUnknown(m)
}

var xxx_messageInfo_GroupActionReq proto.InternalMessageInfo

func (m *GroupActionReq) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *GroupActionReq) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

type GroupActionRsp struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupActionRsp) Reset()         { *m = GroupActionRsp{} }
func (m *GroupActionRsp) String() string { return proto.CompactTextString(m) }
func (*GroupActionRsp) ProtoMessage()    {}
func (*GroupActionRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{2}
}

func (m *GroupActionRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupActionRsp.Unmarshal(m, b)
}
func (m *GroupActionRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupActionRsp.Marshal(b, m, deterministic)
}
func (m *GroupActionRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupActionRsp.Merge(m, src)
}
func (m *GroupActionRsp) XXX_Size() int {
	return xxx_messageInfo_GroupActionRsp.Size(m)
}
func (m *GroupActionRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupActionRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GroupActionRsp proto.InternalMessageInfo

func (m *GroupActionRsp) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

type PubMsgReq struct {
	Msg                  *Msg     `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubMsgReq) Reset()         { *m = PubMsgReq{} }
func (m *PubMsgReq) String() string { return proto.CompactTextString(m) }
func (*PubMsgReq) ProtoMessage()    {}
func (*PubMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{3}
}

func (m *PubMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubMsgReq.Unmarshal(m, b)
}
func (m *PubMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubMsgReq.Marshal(b, m, deterministic)
}
func (m *PubMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubMsgReq.Merge(m, src)
}
func (m *PubMsgReq) XXX_Size() int {
	return xxx_messageInfo_PubMsgReq.Size(m)
}
func (m *PubMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PubMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_PubMsgReq proto.InternalMessageInfo

func (m *PubMsgReq) GetMsg() *Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

type PubMsgRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubMsgRsp) Reset()         { *m = PubMsgRsp{} }
func (m *PubMsgRsp) String() string { return proto.CompactTextString(m) }
func (*PubMsgRsp) ProtoMessage()    {}
func (*PubMsgRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{4}
}

func (m *PubMsgRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubMsgRsp.Unmarshal(m, b)
}
func (m *PubMsgRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubMsgRsp.Marshal(b, m, deterministic)
}
func (m *PubMsgRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubMsgRsp.Merge(m, src)
}
func (m *PubMsgRsp) XXX_Size() int {
	return xxx_messageInfo_PubMsgRsp.Size(m)
}
func (m *PubMsgRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PubMsgRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PubMsgRsp proto.InternalMessageInfo

type Msg struct {
	MsgId                string   `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	FromId               string   `protobuf:"bytes,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId                 string   `protobuf:"bytes,3,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{5}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *Msg) GetFromId() string {
	if m != nil {
		return m.FromId
	}
	return ""
}

func (m *Msg) GetToId() string {
	if m != nil {
		return m.ToId
	}
	return ""
}

func (m *Msg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*ConnReq)(nil), "chat.ConnReq")
	proto.RegisterType((*GroupActionReq)(nil), "chat.GroupActionReq")
	proto.RegisterType((*GroupActionRsp)(nil), "chat.GroupActionRsp")
	proto.RegisterType((*PubMsgReq)(nil), "chat.PubMsgReq")
	proto.RegisterType((*PubMsgRsp)(nil), "chat.PubMsgRsp")
	proto.RegisterType((*Msg)(nil), "chat.Msg")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54) }

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcd, 0x4e, 0xc3, 0x30,
	0x10, 0x84, 0x15, 0x92, 0x26, 0xca, 0x46, 0xfc, 0x68, 0x29, 0x10, 0x85, 0x03, 0xc8, 0xa7, 0x8a,
	0x43, 0x85, 0xca, 0x09, 0x6e, 0xa8, 0x07, 0x94, 0x43, 0x25, 0xd4, 0x17, 0x40, 0x69, 0x1c, 0xdc,
	0x0a, 0xc5, 0x36, 0xb1, 0xfb, 0x20, 0xbc, 0x31, 0x5a, 0x3b, 0x04, 0x22, 0x7a, 0xf3, 0x7c, 0xb3,
	0xb6, 0x66, 0xc7, 0x00, 0xf5, 0xb6, 0xb2, 0x73, 0xdd, 0x29, 0xab, 0x30, 0xa2, 0x33, 0xbb, 0x81,
	0x64, 0xa9, 0xa4, 0x5c, 0x37, 0x9f, 0x38, 0x85, 0x89, 0x55, 0x1f, 0x8d, 0xcc, 0x83, 0xdb, 0x60,
	0x96, 0xae, 0xbd, 0x60, 0x4f, 0x70, 0xf2, 0xd2, 0xa9, 0xbd, 0x7e, 0xae, 0xed, 0x4e, 0xb9, 0xb9,
	0x33, 0x08, 0xc5, 0x8e, 0xf7, 0x53, 0x74, 0xc4, 0x4b, 0x88, 0x2b, 0x67, 0xe7, 0x47, 0x0e, 0xf6,
	0x8a, 0xb1, 0xf1, 0x5d, 0xa3, 0xff, 0xdf, 0x65, 0x33, 0x48, 0x5f, 0xf7, 0x9b, 0x95, 0x11, 0xf4,
	0xf4, 0x35, 0x84, 0xad, 0x11, 0xce, 0xce, 0x16, 0xe9, 0xdc, 0xa5, 0x25, 0x8b, 0x28, 0xcb, 0x86,
	0x49, 0xa3, 0x19, 0x87, 0x70, 0x65, 0x04, 0x5e, 0x40, 0xdc, 0x1a, 0xf1, 0x36, 0x3c, 0x39, 0x69,
	0x8d, 0x28, 0x39, 0x5e, 0x41, 0xf2, 0xde, 0xa9, 0x96, 0x78, 0x9f, 0x88, 0x64, 0xc9, 0xf1, 0x9c,
	0x76, 0x24, 0x1c, 0x3a, 0x1c, 0x59, 0x55, 0x72, 0xcc, 0x21, 0xa9, 0x95, 0xb4, 0x8d, 0xb4, 0x79,
	0xe4, 0xf0, 0x8f, 0x5c, 0x7c, 0x05, 0x10, 0x2d, 0xb7, 0x95, 0x45, 0x06, 0x11, 0xd5, 0x84, 0xc7,
	0x3e, 0x53, 0x5f, 0x59, 0xf1, 0x1b, 0xf1, 0x3e, 0xc0, 0x3b, 0x88, 0x7d, 0x3e, 0x3c, 0xf5, 0x78,
	0xd8, 0xab, 0x18, 0x03, 0xa3, 0xf1, 0x11, 0xb2, 0x3f, 0xcd, 0xe0, 0xd4, 0xfb, 0xe3, 0xa2, 0x8b,
	0x03, 0xd4, 0xe8, 0x4d, 0xec, 0xbe, 0xef, 0xe1, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x28, 0x5c, 0x1c,
	0x91, 0xcc, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatClient interface {
	Conn(ctx context.Context, in *ConnReq, opts ...grpc.CallOption) (Chat_ConnClient, error)
	PubMsg(ctx context.Context, in *PubMsgReq, opts ...grpc.CallOption) (*PubMsgRsp, error)
	GroupAction(ctx context.Context, in *GroupActionReq, opts ...grpc.CallOption) (*GroupActionRsp, error)
}

type chatClient struct {
	cc *grpc.ClientConn
}

func NewChatClient(cc *grpc.ClientConn) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) Conn(ctx context.Context, in *ConnReq, opts ...grpc.CallOption) (Chat_ConnClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Chat_serviceDesc.Streams[0], "/chat.Chat/Conn", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatConnClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Chat_ConnClient interface {
	Recv() (*Msg, error)
	grpc.ClientStream
}

type chatConnClient struct {
	grpc.ClientStream
}

func (x *chatConnClient) Recv() (*Msg, error) {
	m := new(Msg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatClient) PubMsg(ctx context.Context, in *PubMsgReq, opts ...grpc.CallOption) (*PubMsgRsp, error) {
	out := new(PubMsgRsp)
	err := c.cc.Invoke(ctx, "/chat.Chat/PubMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) GroupAction(ctx context.Context, in *GroupActionReq, opts ...grpc.CallOption) (*GroupActionRsp, error) {
	out := new(GroupActionRsp)
	err := c.cc.Invoke(ctx, "/chat.Chat/GroupAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServer is the server API for Chat service.
type ChatServer interface {
	Conn(*ConnReq, Chat_ConnServer) error
	PubMsg(context.Context, *PubMsgReq) (*PubMsgRsp, error)
	GroupAction(context.Context, *GroupActionReq) (*GroupActionRsp, error)
}

func RegisterChatServer(s *grpc.Server, srv ChatServer) {
	s.RegisterService(&_Chat_serviceDesc, srv)
}

func _Chat_Conn_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConnReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServer).Conn(m, &chatConnServer{stream})
}

type Chat_ConnServer interface {
	Send(*Msg) error
	grpc.ServerStream
}

type chatConnServer struct {
	grpc.ServerStream
}

func (x *chatConnServer) Send(m *Msg) error {
	return x.ServerStream.SendMsg(m)
}

func _Chat_PubMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).PubMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Chat/PubMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).PubMsg(ctx, req.(*PubMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_GroupAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).GroupAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Chat/GroupAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).GroupAction(ctx, req.(*GroupActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Chat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PubMsg",
			Handler:    _Chat_PubMsg_Handler,
		},
		{
			MethodName: "GroupAction",
			Handler:    _Chat_GroupAction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Conn",
			Handler:       _Chat_Conn_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chat.proto",
}
