// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package chat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthType int32

const (
	AuthType_NAME_PWD   AuthType = 0
	AuthType_EMAIL_PWD  AuthType = 1
	AuthType_PHONE_PWD  AuthType = 2
	AuthType_PHONE_CODE AuthType = 3
)

var AuthType_name = map[int32]string{
	0: "NAME_PWD",
	1: "EMAIL_PWD",
	2: "PHONE_PWD",
	3: "PHONE_CODE",
}
var AuthType_value = map[string]int32{
	"NAME_PWD":   0,
	"EMAIL_PWD":  1,
	"PHONE_PWD":  2,
	"PHONE_CODE": 3,
}

func (x AuthType) String() string {
	return proto.EnumName(AuthType_name, int32(x))
}
func (AuthType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_chat_ddf8114ad9ac18b0, []int{0}
}

type ContentType int32

const (
	ContentType_TEXT  ContentType = 0
	ContentType_IMAGE ContentType = 1
)

var ContentType_name = map[int32]string{
	0: "TEXT",
	1: "IMAGE",
}
var ContentType_value = map[string]int32{
	"TEXT":  0,
	"IMAGE": 1,
}

func (x ContentType) String() string {
	return proto.EnumName(ContentType_name, int32(x))
}
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_chat_ddf8114ad9ac18b0, []int{1}
}

type MsgType int32

const (
	MsgType_GROUP MsgType = 0
	MsgType_P2P   MsgType = 1
)

var MsgType_name = map[int32]string{
	0: "GROUP",
	1: "P2P",
}
var MsgType_value = map[string]int32{
	"GROUP": 0,
	"P2P":   1,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_chat_ddf8114ad9ac18b0, []int{2}
}

type ConnReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnReq) Reset()         { *m = ConnReq{} }
func (m *ConnReq) String() string { return proto.CompactTextString(m) }
func (*ConnReq) ProtoMessage()    {}
func (*ConnReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_ddf8114ad9ac18b0, []int{0}
}
func (m *ConnReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnReq.Unmarshal(m, b)
}
func (m *ConnReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnReq.Marshal(b, m, deterministic)
}
func (dst *ConnReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnReq.Merge(dst, src)
}
func (m *ConnReq) XXX_Size() int {
	return xxx_messageInfo_ConnReq.Size(m)
}
func (m *ConnReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConnReq proto.InternalMessageInfo

type ConnRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnRsp) Reset()         { *m = ConnRsp{} }
func (m *ConnRsp) String() string { return proto.CompactTextString(m) }
func (*ConnRsp) ProtoMessage()    {}
func (*ConnRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_ddf8114ad9ac18b0, []int{1}
}
func (m *ConnRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnRsp.Unmarshal(m, b)
}
func (m *ConnRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnRsp.Marshal(b, m, deterministic)
}
func (dst *ConnRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnRsp.Merge(dst, src)
}
func (m *ConnRsp) XXX_Size() int {
	return xxx_messageInfo_ConnRsp.Size(m)
}
func (m *ConnRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ConnRsp proto.InternalMessageInfo

type GroupReq struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupReq) Reset()         { *m = GroupReq{} }
func (m *GroupReq) String() string { return proto.CompactTextString(m) }
func (*GroupReq) ProtoMessage()    {}
func (*GroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_ddf8114ad9ac18b0, []int{2}
}
func (m *GroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupReq.Unmarshal(m, b)
}
func (m *GroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupReq.Marshal(b, m, deterministic)
}
func (dst *GroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupReq.Merge(dst, src)
}
func (m *GroupReq) XXX_Size() int {
	return xxx_messageInfo_GroupReq.Size(m)
}
func (m *GroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_GroupReq proto.InternalMessageInfo

func (m *GroupReq) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

type GroupRsp struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupRsp) Reset()         { *m = GroupRsp{} }
func (m *GroupRsp) String() string { return proto.CompactTextString(m) }
func (*GroupRsp) ProtoMessage()    {}
func (*GroupRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_ddf8114ad9ac18b0, []int{3}
}
func (m *GroupRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupRsp.Unmarshal(m, b)
}
func (m *GroupRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupRsp.Marshal(b, m, deterministic)
}
func (dst *GroupRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupRsp.Merge(dst, src)
}
func (m *GroupRsp) XXX_Size() int {
	return xxx_messageInfo_GroupRsp.Size(m)
}
func (m *GroupRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GroupRsp proto.InternalMessageInfo

func (m *GroupRsp) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

type PubReq struct {
	Msg                  *Msg     `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubReq) Reset()         { *m = PubReq{} }
func (m *PubReq) String() string { return proto.CompactTextString(m) }
func (*PubReq) ProtoMessage()    {}
func (*PubReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_ddf8114ad9ac18b0, []int{4}
}
func (m *PubReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubReq.Unmarshal(m, b)
}
func (m *PubReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubReq.Marshal(b, m, deterministic)
}
func (dst *PubReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubReq.Merge(dst, src)
}
func (m *PubReq) XXX_Size() int {
	return xxx_messageInfo_PubReq.Size(m)
}
func (m *PubReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PubReq.DiscardUnknown(m)
}

var xxx_messageInfo_PubReq proto.InternalMessageInfo

func (m *PubReq) GetMsg() *Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

type PubRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubRsp) Reset()         { *m = PubRsp{} }
func (m *PubRsp) String() string { return proto.CompactTextString(m) }
func (*PubRsp) ProtoMessage()    {}
func (*PubRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_ddf8114ad9ac18b0, []int{5}
}
func (m *PubRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubRsp.Unmarshal(m, b)
}
func (m *PubRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubRsp.Marshal(b, m, deterministic)
}
func (dst *PubRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubRsp.Merge(dst, src)
}
func (m *PubRsp) XXX_Size() int {
	return xxx_messageInfo_PubRsp.Size(m)
}
func (m *PubRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PubRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PubRsp proto.InternalMessageInfo

type Msg struct {
	MsgType              MsgType     `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=chat.MsgType" json:"msg_type,omitempty"`
	MsgId                string      `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	FromId               string      `protobuf:"bytes,3,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId                 string      `protobuf:"bytes,4,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	ContentType          ContentType `protobuf:"varint,5,opt,name=content_type,json=contentType,proto3,enum=chat.ContentType" json:"content_type,omitempty"`
	Content              string      `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Name                 string      `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_ddf8114ad9ac18b0, []int{6}
}
func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (dst *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(dst, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetMsgType() MsgType {
	if m != nil {
		return m.MsgType
	}
	return MsgType_GROUP
}

func (m *Msg) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *Msg) GetFromId() string {
	if m != nil {
		return m.FromId
	}
	return ""
}

func (m *Msg) GetToId() string {
	if m != nil {
		return m.ToId
	}
	return ""
}

func (m *Msg) GetContentType() ContentType {
	if m != nil {
		return m.ContentType
	}
	return ContentType_TEXT
}

func (m *Msg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Msg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ConnReq)(nil), "chat.ConnReq")
	proto.RegisterType((*ConnRsp)(nil), "chat.ConnRsp")
	proto.RegisterType((*GroupReq)(nil), "chat.GroupReq")
	proto.RegisterType((*GroupRsp)(nil), "chat.GroupRsp")
	proto.RegisterType((*PubReq)(nil), "chat.PubReq")
	proto.RegisterType((*PubRsp)(nil), "chat.PubRsp")
	proto.RegisterType((*Msg)(nil), "chat.Msg")
	proto.RegisterEnum("chat.AuthType", AuthType_name, AuthType_value)
	proto.RegisterEnum("chat.ContentType", ContentType_name, ContentType_value)
	proto.RegisterEnum("chat.MsgType", MsgType_name, MsgType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatClient interface {
	Conn(ctx context.Context, in *ConnReq, opts ...grpc.CallOption) (Chat_ConnClient, error)
	Pub(ctx context.Context, in *PubReq, opts ...grpc.CallOption) (*PubRsp, error)
	Group(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*GroupRsp, error)
}

type chatClient struct {
	cc *grpc.ClientConn
}

func NewChatClient(cc *grpc.ClientConn) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) Conn(ctx context.Context, in *ConnReq, opts ...grpc.CallOption) (Chat_ConnClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Chat_serviceDesc.Streams[0], "/chat.Chat/Conn", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatConnClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Chat_ConnClient interface {
	Recv() (*Msg, error)
	grpc.ClientStream
}

type chatConnClient struct {
	grpc.ClientStream
}

func (x *chatConnClient) Recv() (*Msg, error) {
	m := new(Msg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatClient) Pub(ctx context.Context, in *PubReq, opts ...grpc.CallOption) (*PubRsp, error) {
	out := new(PubRsp)
	err := c.cc.Invoke(ctx, "/chat.Chat/Pub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) Group(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*GroupRsp, error) {
	out := new(GroupRsp)
	err := c.cc.Invoke(ctx, "/chat.Chat/Group", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServer is the server API for Chat service.
type ChatServer interface {
	Conn(*ConnReq, Chat_ConnServer) error
	Pub(context.Context, *PubReq) (*PubRsp, error)
	Group(context.Context, *GroupReq) (*GroupRsp, error)
}

func RegisterChatServer(s *grpc.Server, srv ChatServer) {
	s.RegisterService(&_Chat_serviceDesc, srv)
}

func _Chat_Conn_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConnReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServer).Conn(m, &chatConnServer{stream})
}

type Chat_ConnServer interface {
	Send(*Msg) error
	grpc.ServerStream
}

type chatConnServer struct {
	grpc.ServerStream
}

func (x *chatConnServer) Send(m *Msg) error {
	return x.ServerStream.SendMsg(m)
}

func _Chat_Pub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).Pub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Chat/Pub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).Pub(ctx, req.(*PubReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_Group_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).Group(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Chat/Group",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).Group(ctx, req.(*GroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Chat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pub",
			Handler:    _Chat_Pub_Handler,
		},
		{
			MethodName: "Group",
			Handler:    _Chat_Group_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Conn",
			Handler:       _Chat_Conn_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chat.proto",
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_chat_ddf8114ad9ac18b0) }

var fileDescriptor_chat_ddf8114ad9ac18b0 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xdb, 0xca, 0xd3, 0x40,
	0x14, 0x85, 0x9b, 0x3f, 0xe7, 0xdd, 0x03, 0x71, 0x8b, 0x18, 0xaa, 0x82, 0x06, 0xc4, 0x9f, 0x5e,
	0xfc, 0x48, 0xf4, 0x05, 0x42, 0x1a, 0x6b, 0xc0, 0xb4, 0x21, 0x54, 0xf4, 0xae, 0xb4, 0x4d, 0x4c,
	0x7b, 0x91, 0xcc, 0xb4, 0x33, 0x11, 0xfa, 0xa6, 0x3e, 0x8e, 0xcc, 0x4c, 0x4f, 0x82, 0x77, 0xeb,
	0x5b, 0x6b, 0x76, 0x56, 0x92, 0x3d, 0x00, 0xdb, 0xdd, 0x9a, 0x3f, 0xd1, 0x23, 0xe1, 0x04, 0x0d,
	0xa1, 0x03, 0x17, 0xec, 0x98, 0xb4, 0x6d, 0x51, 0x1d, 0xae, 0x92, 0xd1, 0xe0, 0x35, 0x38, 0xb3,
	0x23, 0xe9, 0x68, 0x51, 0x1d, 0xd0, 0x03, 0xbd, 0xde, 0x97, 0xbe, 0xf6, 0x56, 0x7b, 0x74, 0x0b,
	0x21, 0x6f, 0x29, 0xa3, 0xff, 0x49, 0xdf, 0x83, 0x95, 0x77, 0x1b, 0x31, 0xf9, 0x0a, 0xf4, 0x86,
	0xd5, 0x32, 0xeb, 0x87, 0xee, 0x93, 0xec, 0xce, 0x58, 0x5d, 0x08, 0x37, 0x70, 0xd4, 0x31, 0x46,
	0x83, 0x3f, 0x1a, 0xe8, 0x19, 0xab, 0xf1, 0x11, 0x9c, 0x86, 0xd5, 0x2b, 0x7e, 0xa2, 0x95, 0x9c,
	0x19, 0x85, 0xc3, 0xeb, 0xcc, 0xf2, 0x44, 0xab, 0xc2, 0x6e, 0x94, 0xc0, 0x17, 0x60, 0x89, 0x93,
	0xfb, 0xd2, 0x7f, 0x90, 0xbd, 0x66, 0xc3, 0xea, 0xb4, 0xc4, 0x97, 0x60, 0xff, 0x3a, 0x92, 0x46,
	0xf8, 0xba, 0xf4, 0x2d, 0x81, 0x69, 0x89, 0xcf, 0xc1, 0xe4, 0x44, 0xd8, 0x86, 0xb4, 0x0d, 0x4e,
	0xd2, 0x12, 0x3f, 0xc3, 0x60, 0x4b, 0x5a, 0x5e, 0xb5, 0x5c, 0x55, 0x9a, 0xb2, 0xf2, 0x99, 0xaa,
	0x8c, 0x55, 0x22, 0x6b, 0xfb, 0xdb, 0x1b, 0xa0, 0x0f, 0xf6, 0x19, 0x7d, 0x4b, 0x3e, 0xec, 0x82,
	0x88, 0x60, 0xb4, 0xeb, 0xa6, 0xf2, 0x6d, 0xd5, 0x21, 0xf4, 0xe4, 0x0b, 0x38, 0x51, 0xc7, 0x77,
	0x72, 0x72, 0x00, 0xce, 0x3c, 0xca, 0x92, 0x55, 0xfe, 0x63, 0xea, 0xf5, 0x70, 0x08, 0x6e, 0x92,
	0x45, 0xe9, 0x37, 0x89, 0x9a, 0xc0, 0xfc, 0xeb, 0x62, 0xae, 0xd2, 0x07, 0x1c, 0x01, 0x28, 0x8c,
	0x17, 0xd3, 0xc4, 0xd3, 0x27, 0x01, 0xf4, 0xef, 0xde, 0x08, 0x1d, 0x30, 0x96, 0xc9, 0xcf, 0xa5,
	0xd7, 0x43, 0x17, 0xcc, 0x34, 0x8b, 0x66, 0x89, 0xa7, 0x4d, 0xde, 0x80, 0x7d, 0xfe, 0x51, 0xc2,
	0x9d, 0x15, 0x8b, 0xef, 0xb9, 0xd7, 0x43, 0x1b, 0xf4, 0x3c, 0xcc, 0x3d, 0x2d, 0xfc, 0x0d, 0x46,
	0xbc, 0x5b, 0x73, 0x0c, 0xc0, 0x10, 0x5b, 0xc6, 0xe1, 0xf5, 0x43, 0xc5, 0xf2, 0xc7, 0xb7, 0xf5,
	0x7c, 0xd4, 0xf0, 0x1d, 0xe8, 0x79, 0xb7, 0xc1, 0x81, 0xf2, 0xd4, 0x36, 0xc7, 0x77, 0xc4, 0x28,
	0x7e, 0x00, 0x53, 0xde, 0x01, 0x1c, 0x29, 0xfb, 0x72, 0x5d, 0xc6, 0xff, 0x30, 0xa3, 0x1b, 0x4b,
	0xde, 0xb6, 0x4f, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x14, 0x70, 0xe1, 0x7b, 0x02, 0x00,
	0x00,
}
